### ISSUE TITLE
Replace `alias` with `ln -s`

### ISSUE THREAD

**Issue by chinsyo** [Quxiaolei/XLLog#1]
ln -s ALTOOL_PATH DEST_PATH (/usr/local/bin/altool for me)

**Comment by Quxiaolei** [comment]
Yep, symbolic Link will be better(6ecf776fb3634180741fbfe2f797f5142624306a)
Refs:[https://quxiaolei.github.io/使用工具进行APP打包和分发.html#ipa包的处理](https://quxiaolei.github.io/%E4%BD%BF%E7%94%A8%E5%B7%A5%E5%85%B7%E8%BF%9B%E8%A1%8CAPP%E6%89%93%E5%8C%85%E5%92%8C%E5%88%86%E5%8F%91.html#ipa%E5%8C%85%E7%9A%84%E5%A4%84%E7%90%86)
